#include <TargetConditionals.h>
#if TARGET_OS_SIMULATOR
#if 0
#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef ENCRYPTION_SWIFT_H
#define ENCRYPTION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X)
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X)
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X)
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Encryption",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("AccountGroupMO")
@interface AccountGroupMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@class NSString;

@interface AccountGroupMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable invite_by;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@end


SWIFT_CLASS_NAMED("AccountKeyMO")
@interface AccountKeyMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface AccountKeyMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic) int32_t last_resort;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable public_key;
@property (nonatomic, copy) NSString * _Nullable signature;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@property (nonatomic, copy) NSString * _Nullable uuid;
@end


SWIFT_CLASS_NAMED("AccountMO")
@interface AccountMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface AccountMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable avatarId;
@property (nonatomic, copy) NSString * _Nullable background_id;
@property (nonatomic, copy) NSString * _Nullable birthday;
@property (nonatomic) int64_t block_time;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable first_name;
@property (nonatomic) int16_t gender;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable last_name;
@property (nonatomic, copy) NSString * _Nullable mail;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable pin;
@property (nonatomic) int32_t region_code;
@property (nonatomic) int32_t resendTimes;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@property (nonatomic) int32_t verifyTimes;
@end


SWIFT_CLASS_NAMED("ApiCallMO")
@interface ApiCallMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ApiCallMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable original_content;
@property (nonatomic, copy) NSString * _Nullable original_uid;
@property (nonatomic, copy) NSString * _Nullable query;
@property (nonatomic) int64_t retry;
@property (nonatomic, copy) NSString * _Nullable task;
@end


SWIFT_CLASS_NAMED("BranchAccountMO")
@interface BranchAccountMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface BranchAccountMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t state;
@end


SWIFT_CLASS_NAMED("BranchMO")
@interface BranchMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface BranchMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable attachment_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable domain;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable public_ip;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@end


SWIFT_CLASS_NAMED("CallHistoryMO")
@interface CallHistoryMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface CallHistoryMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic, copy) NSString * _Nullable calling_members;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic) int16_t group_type;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable joined_members;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable parent_id;
@property (nonatomic, copy) NSString * _Nullable room_id;
@property (nonatomic, copy) NSString * _Nullable sender_id;
@property (nonatomic, copy) NSString * _Nullable source_id;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@property (nonatomic) int16_t type;
@end


SWIFT_CLASS_NAMED("ContactMO")
@interface ContactMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface ContactMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic, copy) NSString * _Nullable contact_id;
@property (nonatomic, copy) NSString * _Nullable contact_name;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@end


SWIFT_CLASS_NAMED("DeviceMO")
@interface DeviceMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DeviceMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int16_t key_f;
@property (nonatomic) int64_t last_seen;
@property (nonatomic) int16_t master_f;
@property (nonatomic, copy) NSString * _Nullable model_number;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable public_key;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@property (nonatomic) int64_t version;
@end


SWIFT_CLASS_NAMED("EmojiMO")
@interface EmojiMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface EmojiMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable decode;
@property (nonatomic, copy) NSString * _Nullable emoji_group;
@property (nonatomic, copy) NSString * _Nullable hex_code;
@property (nonatomic) int16_t id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t state;
@property (nonatomic, copy) NSString * _Nullable version;
@end

@class NSData;
@class SDKDataResponse;

SWIFT_PROTOCOL_NAMED("EncryptionProtocol")
@protocol EncryptionProtocol
- (NSString * _Nonnull)loginWithThirdPartyToken:(NSString * _Nonnull)thirdPartyToken thirdServiceId:(NSString * _Nonnull)thirdServiceId userId:(NSString * _Nonnull)userId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)sendTextWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds text:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTextWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)sendFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds buffer:(NSData * _Nonnull)buffer SWIFT_WARN_UNUSED_RESULT;
- (SDKDataResponse * _Nonnull)getFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)deleteFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)updatePermissionWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)restoreWithToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)logout SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("Encryption")
@interface Encryption : NSObject <EncryptionProtocol>
- (NSString * _Nonnull)loginWithThirdPartyToken:(NSString * _Nonnull)thirdPartyToken thirdServiceId:(NSString * _Nonnull)thirdServiceId userId:(NSString * _Nonnull)userId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)sendTextWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds text:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTextWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)sendFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds buffer:(NSData * _Nonnull)buffer SWIFT_WARN_UNUSED_RESULT;
- (SDKDataResponse * _Nonnull)getFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)deleteFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)updatePermissionWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)backupWithToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)restoreWithToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)logout SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("ErrorMessageRetryMO")
@interface ErrorMessageRetryMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ErrorMessageRetryMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t retry;
@property (nonatomic, copy) NSString * _Nullable source_id;
@property (nonatomic) int16_t state;
@end


SWIFT_CLASS_NAMED("ErrorMessageSendNullMO")
@interface ErrorMessageSendNullMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ErrorMessageSendNullMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t retry;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@end



SWIFT_CLASS_NAMED("GroupMO")
@interface GroupMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface GroupMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable avatar_id;
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable created_by;
@property (nonatomic) int16_t display_state;
@property (nonatomic) int16_t encryption_f;
@property (nonatomic) int16_t group_type;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t private_f;
@property (nonatomic) int64_t seen_time;
@property (nonatomic) int16_t state;
@end


SWIFT_CLASS_NAMED("GroupSettingMO")
@interface GroupSettingMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface GroupSettingMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable setting_id;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@end



SWIFT_CLASS_NAMED("IdentityKeyMO")
@interface IdentityKeyMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface IdentityKeyMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic) int32_t id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable public_key;
@end


SWIFT_CLASS_NAMED("MessageMO")
@interface MessageMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface MessageMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int16_t call_status;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable content_decode;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable mentions;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable parent_id;
@property (nonatomic) int16_t send_type;
@property (nonatomic, copy) NSString * _Nullable sender_device_id;
@property (nonatomic, copy) NSString * _Nullable sender_id;
@property (nonatomic, copy) NSString * _Nullable source_id;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@property (nonatomic, copy) NSString * _Nullable third_party_id;
@property (nonatomic, copy) NSString * _Nullable thread_id;
@end





SWIFT_CLASS_NAMED("NotificationMO")
@interface NotificationMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface NotificationMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable from_account_id;
@property (nonatomic, copy) NSString * _Nullable from_device_id;
@property (nonatomic, copy) NSString * _Nullable from_group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable mentions;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable notice_to_account_id;
@property (nonatomic, copy) NSString * _Nullable notice_to_device_id;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable parent;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@property (nonatomic) int16_t type;
@end


SWIFT_CLASS_NAMED("OneTimePreKeysMO")
@interface OneTimePreKeysMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface OneTimePreKeysMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t id;
@property (nonatomic) int64_t key_id;
@property (nonatomic, copy) NSString * _Nullable private_key;
@property (nonatomic, copy) NSString * _Nullable public_key;
@end


SWIFT_CLASS("_TtC10Encryption15SDKDataResponse")
@interface SDKDataResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SenderKeySharedMO")
@interface SenderKeySharedMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface SenderKeySharedMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic) int64_t id;
@end


SWIFT_CLASS_NAMED("SenderKeysMO")
@interface SenderKeysMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface SenderKeysMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic) int64_t created_at;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic) int64_t id;
@property (nonatomic) int64_t index_send_number;
@property (nonatomic, copy) NSString * _Nullable record;
@end


SWIFT_CLASS_NAMED("SessionsMO")
@interface SessionsMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface SessionsMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic) int64_t id;
@property (nonatomic) int64_t index_send_number;
@property (nonatomic, copy) NSString * _Nullable record;
@end


SWIFT_CLASS_NAMED("SettingMO")
@interface SettingMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface SettingMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable descriptions;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t object_type;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t setting_type;
@property (nonatomic) int16_t state;
@end


SWIFT_CLASS_NAMED("SignedPreKeysMO")
@interface SignedPreKeysMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface SignedPreKeysMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t id;
@property (nonatomic) int64_t key_id;
@property (nonatomic, copy) NSString * _Nullable private_key;
@property (nonatomic, copy) NSString * _Nullable public_key;
@property (nonatomic, copy) NSString * _Nullable signature;
@property (nonatomic) int64_t timestamp;
@end


SWIFT_CLASS_NAMED("TextSearchMO")
@interface TextSearchMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface TextSearchMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable search_history;
@property (nonatomic) int16_t state;
@end



#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif

#else
#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef ENCRYPTION_SWIFT_H
#define ENCRYPTION_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X)
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X)
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X)
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreData;
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Encryption",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSEntityDescription;
@class NSManagedObjectContext;

SWIFT_CLASS_NAMED("AccountGroupMO")
@interface AccountGroupMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@class NSString;

@interface AccountGroupMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable invite_by;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@end


SWIFT_CLASS_NAMED("AccountKeyMO")
@interface AccountKeyMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface AccountKeyMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic) int32_t last_resort;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable public_key;
@property (nonatomic, copy) NSString * _Nullable signature;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@property (nonatomic, copy) NSString * _Nullable uuid;
@end


SWIFT_CLASS_NAMED("AccountMO")
@interface AccountMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface AccountMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable address;
@property (nonatomic, copy) NSString * _Nullable avatarId;
@property (nonatomic, copy) NSString * _Nullable background_id;
@property (nonatomic, copy) NSString * _Nullable birthday;
@property (nonatomic) int64_t block_time;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable first_name;
@property (nonatomic) int16_t gender;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable last_name;
@property (nonatomic, copy) NSString * _Nullable mail;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable phone;
@property (nonatomic, copy) NSString * _Nullable pin;
@property (nonatomic) int32_t region_code;
@property (nonatomic) int32_t resendTimes;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@property (nonatomic) int32_t verifyTimes;
@end


SWIFT_CLASS_NAMED("ApiCallMO")
@interface ApiCallMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ApiCallMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable original_content;
@property (nonatomic, copy) NSString * _Nullable original_uid;
@property (nonatomic, copy) NSString * _Nullable query;
@property (nonatomic) int64_t retry;
@property (nonatomic, copy) NSString * _Nullable task;
@end


SWIFT_CLASS_NAMED("BranchAccountMO")
@interface BranchAccountMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface BranchAccountMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t state;
@end


SWIFT_CLASS_NAMED("BranchMO")
@interface BranchMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface BranchMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable attachment_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable domain;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable public_ip;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@end


SWIFT_CLASS_NAMED("CallHistoryMO")
@interface CallHistoryMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface CallHistoryMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic, copy) NSString * _Nullable calling_members;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic) int16_t group_type;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable joined_members;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable parent_id;
@property (nonatomic, copy) NSString * _Nullable room_id;
@property (nonatomic, copy) NSString * _Nullable sender_id;
@property (nonatomic, copy) NSString * _Nullable source_id;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@property (nonatomic) int16_t type;
@end


SWIFT_CLASS_NAMED("ContactMO")
@interface ContactMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface ContactMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic, copy) NSString * _Nullable contact_id;
@property (nonatomic, copy) NSString * _Nullable contact_name;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@end


SWIFT_CLASS_NAMED("DeviceMO")
@interface DeviceMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface DeviceMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int16_t key_f;
@property (nonatomic) int64_t last_seen;
@property (nonatomic) int16_t master_f;
@property (nonatomic, copy) NSString * _Nullable model_number;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable public_key;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@property (nonatomic) int64_t version;
@end


SWIFT_CLASS_NAMED("EmojiMO")
@interface EmojiMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface EmojiMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable decode;
@property (nonatomic, copy) NSString * _Nullable emoji_group;
@property (nonatomic, copy) NSString * _Nullable hex_code;
@property (nonatomic) int16_t id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t state;
@property (nonatomic, copy) NSString * _Nullable version;
@end

@class NSData;
@class SDKDataResponse;

SWIFT_PROTOCOL_NAMED("EncryptionProtocol")
@protocol EncryptionProtocol
- (NSString * _Nonnull)loginWithThirdPartyToken:(NSString * _Nonnull)thirdPartyToken thirdServiceId:(NSString * _Nonnull)thirdServiceId userId:(NSString * _Nonnull)userId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)sendTextWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds text:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTextWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)sendFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds buffer:(NSData * _Nonnull)buffer SWIFT_WARN_UNUSED_RESULT;
- (SDKDataResponse * _Nonnull)getFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)deleteFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)updatePermissionWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)restoreWithToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)logout SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS_NAMED("Encryption")
@interface Encryption : NSObject <EncryptionProtocol>
- (NSString * _Nonnull)loginWithThirdPartyToken:(NSString * _Nonnull)thirdPartyToken thirdServiceId:(NSString * _Nonnull)thirdServiceId userId:(NSString * _Nonnull)userId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)sendTextWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds text:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getTextWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)sendFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds buffer:(NSData * _Nonnull)buffer SWIFT_WARN_UNUSED_RESULT;
- (SDKDataResponse * _Nonnull)getFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)deleteFileWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)updatePermissionWithToken:(NSString * _Nonnull)token thirdPartyId:(NSString * _Nonnull)thirdPartyId userIds:(NSArray<NSString *> * _Nonnull)userIds SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)backupWithToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)restoreWithToken:(NSString * _Nonnull)token SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)logout SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS_NAMED("ErrorMessageRetryMO")
@interface ErrorMessageRetryMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ErrorMessageRetryMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t retry;
@property (nonatomic, copy) NSString * _Nullable source_id;
@property (nonatomic) int16_t state;
@end


SWIFT_CLASS_NAMED("ErrorMessageSendNullMO")
@interface ErrorMessageSendNullMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface ErrorMessageSendNullMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t retry;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t type;
@end



SWIFT_CLASS_NAMED("GroupMO")
@interface GroupMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface GroupMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable avatar_id;
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable created_by;
@property (nonatomic) int16_t display_state;
@property (nonatomic) int16_t encryption_f;
@property (nonatomic) int16_t group_type;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t private_f;
@property (nonatomic) int64_t seen_time;
@property (nonatomic) int16_t state;
@end


SWIFT_CLASS_NAMED("GroupSettingMO")
@interface GroupSettingMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end





@interface GroupSettingMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable setting_id;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@end



SWIFT_CLASS_NAMED("IdentityKeyMO")
@interface IdentityKeyMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface IdentityKeyMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic) int32_t id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable public_key;
@end


SWIFT_CLASS_NAMED("MessageMO")
@interface MessageMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface MessageMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic) int16_t call_status;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic, copy) NSString * _Nullable content_decode;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable mentions;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable parent_id;
@property (nonatomic) int16_t send_type;
@property (nonatomic, copy) NSString * _Nullable sender_device_id;
@property (nonatomic, copy) NSString * _Nullable sender_id;
@property (nonatomic, copy) NSString * _Nullable source_id;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@property (nonatomic, copy) NSString * _Nullable third_party_id;
@property (nonatomic, copy) NSString * _Nullable thread_id;
@end





SWIFT_CLASS_NAMED("NotificationMO")
@interface NotificationMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface NotificationMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable branch_id;
@property (nonatomic, copy) NSString * _Nullable content;
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable from_account_id;
@property (nonatomic, copy) NSString * _Nullable from_device_id;
@property (nonatomic, copy) NSString * _Nullable from_group_id;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable mentions;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable notice_to_account_id;
@property (nonatomic, copy) NSString * _Nullable notice_to_device_id;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic, copy) NSString * _Nullable parent;
@property (nonatomic) int16_t state;
@property (nonatomic) int16_t status;
@property (nonatomic) int16_t type;
@end


SWIFT_CLASS_NAMED("OneTimePreKeysMO")
@interface OneTimePreKeysMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface OneTimePreKeysMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t id;
@property (nonatomic) int64_t key_id;
@property (nonatomic, copy) NSString * _Nullable private_key;
@property (nonatomic, copy) NSString * _Nullable public_key;
@end


SWIFT_CLASS("_TtC10Encryption15SDKDataResponse")
@interface SDKDataResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("SenderKeySharedMO")
@interface SenderKeySharedMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface SenderKeySharedMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic) int64_t id;
@end


SWIFT_CLASS_NAMED("SenderKeysMO")
@interface SenderKeysMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface SenderKeysMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic) int64_t created_at;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic) int64_t id;
@property (nonatomic) int64_t index_send_number;
@property (nonatomic, copy) NSString * _Nullable record;
@end


SWIFT_CLASS_NAMED("SessionsMO")
@interface SessionsMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface SessionsMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic, copy) NSString * _Nullable account_id;
@property (nonatomic, copy) NSString * _Nullable device_id;
@property (nonatomic, copy) NSString * _Nullable group_id;
@property (nonatomic) int64_t id;
@property (nonatomic) int64_t index_send_number;
@property (nonatomic, copy) NSString * _Nullable record;
@end


SWIFT_CLASS_NAMED("SettingMO")
@interface SettingMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end



@interface SettingMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable descriptions;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic) int16_t object_type;
@property (nonatomic, copy) NSString * _Nullable options;
@property (nonatomic) int16_t setting_type;
@property (nonatomic) int16_t state;
@end


SWIFT_CLASS_NAMED("SignedPreKeysMO")
@interface SignedPreKeysMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end






@interface SignedPreKeysMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t id;
@property (nonatomic) int64_t key_id;
@property (nonatomic, copy) NSString * _Nullable private_key;
@property (nonatomic, copy) NSString * _Nullable public_key;
@property (nonatomic, copy) NSString * _Nullable signature;
@property (nonatomic) int64_t timestamp;
@end


SWIFT_CLASS_NAMED("TextSearchMO")
@interface TextSearchMO : NSManagedObject
- (nonnull instancetype)initWithEntity:(NSEntityDescription * _Nonnull)entity insertIntoManagedObjectContext:(NSManagedObjectContext * _Nullable)context OBJC_DESIGNATED_INITIALIZER;
@end




@interface TextSearchMO (SWIFT_EXTENSION(Encryption))
@property (nonatomic) int64_t created;
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic) int64_t modified;
@property (nonatomic, copy) NSString * _Nullable search_history;
@property (nonatomic) int16_t state;
@end



#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif

#endif

